In [1]:
"""
np.insert(array,index,value,axis = None)
array - original array
index - position
value
axis , axis = 0 -> row wise
     , axis = 1 -> column wise
"""

'\nnp.insert(array,index,value,axis = None)\narray - original array\nindex - position\nvalue\naxis , axis = 0 -> row wise\n     , axis = 1 -> column wise\n'

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
new_arr = np.insert(arr,6,70,axis=0)
print(new_arr)

[10 20 30 40 50 60 70]


In [3]:
# insert in 2d
arr_2d = np.array([[1,2],
                   [3,4]])
print(arr_2d)
new_arr = np.insert(arr_2d, 1, [5,6],axis=1)
new_arr

[[1 2]
 [3 4]]


array([[1, 5, 2],
       [3, 6, 4]])

# Append() method

In [5]:
# add element at the end
# np.append(arr, [val1,val2...valn])

import numpy as np
arr = np.array([10,20,30])
new_arr = np.append(arr, [40,50,60])
print(new_arr)

[10 20 30 40 50 60]


# delete() method

In [6]:
"""
np.delete(arr, index, axis = None)
flatten array
"""
arr = np.array([10,20,30,40,50,60])
new_arr = np.delete(arr , 1, axis=None)
new_arr

array([10, 30, 40, 50, 60])

In [7]:
"""
aixs 0 remove row
axis 1 remove column
"""
my_array = np.array([[[1,2,3],
                      [4,5,6],
                      [7,8,9],],
                      [[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
print(my_array)
newarr = np.delete(my_array,1,axis=0)
newarr

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# concate() method

In [8]:
"""
join two array
np.concatenate((arr1,arr2), axis = 0)
axis 0 - vartical staking
axis 1 - horizontal staking
"""
arr1 = np.array([[1,2,3],
                 [8,8,8]])
arr2 = np.array([[4,5,6],
                 [9,9,9]])
new_arr = np.concatenate((arr1, arr2), axis = 1)
new_arr

array([[1, 2, 3, 4, 5, 6],
       [8, 8, 8, 9, 9, 9]])