In [1]:
import numpy as np

In [2]:
arr = np.zeros(3)

In [3]:
arr

array([0., 0., 0.])

In [4]:
my_arr = np.zeros(4)
my_arr

array([0., 0., 0., 0.])

In [6]:
my_arr = np.ones(5)
my_arr

array([1., 1., 1., 1., 1.])

In [7]:
my_arr = np.full((3,3),7)
my_arr

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [8]:
my_arr = np.eye(3)
my_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
my_arr = np.zeros((3,3))
my_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
my_arr = np.ones((3,3))
my_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
# arange()  create a sequence of numbers
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])