In [4]:
# What is Broadcasting?
# Broadcasting is a feature that allows NumPy to perform operations on arrays of different shapes without manually copying data.
# Instead of creating a larger array, NumPy automatically expands the smaller array where possible

In [5]:
import numpy as np

In [6]:
# Adding a Number to an Array
arr = np.array([10, 20, 30, 40])
result = arr + 5
result

array([15, 25, 35, 45])

In [7]:
# Adding Two Arrays
a = np.array([1,2,3])
b = np.array([10,20,30])
a + b

array([11, 22, 33])

In [10]:
# Broadcasting Row-wise
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([10,20,30])
A + B

array([[11, 22, 33],
       [14, 25, 36]])

In [11]:
# Broadcasting Column-wise
A = np.array([[1,2,3],
              [4,5,6]])
B = np.array([[10],
              [20]])
A + B

array([[11, 12, 13],
       [24, 25, 26]])

In [ ]:
# Broadcasting Rules

# Two dimensions are compatible if:

# They are equal.
# One of them is 1


# What is Vectorization?

In [12]:
# Vectorization means performing operations on an entire array at once instead of using Python loops.

# Vectorized code is:

# Faster
# Shorter
# Easier to read

In [14]:
# Without Vectorization
arr = np.array([1,2,3,4])
result = []
for i in arr:
    result.append(i * 2)
print(result)

[np.int64(2), np.int64(4), np.int64(6), np.int64(8)]


In [16]:
# With Vectorization
arr = np.array([1,2,3,4])
arr * 2

array([2, 4, 6, 8])

In [20]:
# Addition
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

In [18]:
# Square Every Element
arr = np.array([1,2,3,4])

arr ** 2

array([ 1,  4,  9, 16])

In [21]:
# Square Root
arr = np.array([4,9,16,25])
np.sqrt(arr)

array([2., 3., 4., 5.])