# Welome to numpy tutorial


**this a heading**

In [2]:
import numpy as np
arr1 = np.array([1,2,34,4,54],np.int8)
arr1

array([ 1,  2, 34,  4, 54], dtype=int8)

In [5]:
arr1[1]


np.int8(2)

In [6]:
arr2 = np.array([1,2,3])
arr2.shape

(3,)

In [7]:
arr2.dtype

dtype('int64')

In [8]:
arr2.size

3

In [10]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
my_arr[0][1]

np.int64(2)

In [12]:
arr = np.array([10,20,30,40,50,60])
arr[arr>25]

array([30, 40, 50, 60])

In [14]:
arr[[0,1,2,3]]

array([10, 20, 30, 40])

In [15]:
arr[-1]

np.int64(60)

In [16]:
arr[1:4]

array([20, 30, 40])

In [17]:
arr[::-1]

array([60, 50, 40, 30, 20, 10])

1