# Handling Missing Values in NumPy

In [ ]:
# NumPy represents missing numeric values using:
# np.nan

In [2]:
import numpy as np

In [6]:
# Creating Missing Values
arr = np.array([10,20,np.nan,40,50])

arr

array([10., 20., nan, 40., 50.])

In [7]:
# Check Missing Values
arr = np.array([10,20,np.nan,40])

np.isnan(arr)

array([False, False,  True, False])

In [8]:
# Count Missing Values
arr = np.array([10,np.nan,20,np.nan,30])

np.sum(np.isnan(arr))

np.int64(2)

In [9]:
# Remove Missing Values
arr = np.array([10,np.nan,20,30,np.nan])

clean = arr[~np.isnan(arr)]

clean

array([10., 20., 30.])

In [15]:
# Replace Missing Values
arr = np.array([10,np.nan,20,np.nan])

arr[np.isnan(arr)] = 0
arr = np.nan_to_num(arr,nan = 100)  #default val ke liye
cleaned_arr2 = np.nan_to_num(arr, nan = 100)


arr

array([10.,  0., 20.,  0.])

In [16]:
# Replace with Mean
arr = np.array([10,np.nan,20,30])

mean = np.nanmean(arr)

arr[np.isnan(arr)] = mean

arr

array([10., 20., 20., 30.])

In [17]:
# Useful Functions for Missing Values
arr = np.array([10,np.nan,20,30])

print(np.nansum(arr))
print(np.nanmean(arr))
print(np.nanmax(arr))

60.0
20.0
30.0
