In [2]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [3]:
"Sum",np.sum(arr)

('Sum', np.int64(210))

In [5]:
"Average",np.mean(arr)

('Average', np.float64(35.0))

In [6]:
"Min",np.min(arr)

('Min', np.int64(10))

In [7]:
"Max",np.max(arr)

('Max', np.int64(60))

In [8]:
"Standard Deviation:",np.std(arr)

('Standard Deviation:', np.float64(17.07825127659933))

In [9]:
"Variance",np.var(arr)

('Variance', np.float64(291.6666666666667))

# astype

In [10]:
arr = np.array([1.2,3.5,2.5,4.3,5.2])
arr.dtype              

dtype('float64')

In [11]:
int_arr = arr.astype(int)
int_arr

array([1, 3, 2, 4, 5])

In [12]:
int_arr.dtype

dtype('int64')

# maths calculation

In [13]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[2,4,6],[1,3,5]])
arr1+arr2

array([[ 3,  6,  9],
       [ 5,  8, 11]])

In [14]:
arr1-arr2

array([[-1, -2, -3],
       [ 3,  2,  1]])

In [15]:
arr1*arr2

array([[ 2,  8, 18],
       [ 4, 15, 30]])

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr1

array([1, 2, 3, 4, 5])

In [22]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [24]:
arr1.ndim

1

In [25]:
arr2.ndim

2

In [26]:
arr3.ndim

3

In [27]:
arr1.size

5

In [28]:
arr2.size

9

In [29]:
arr3.size

12

In [30]:
arr1.shape

(5,)

In [31]:
arr2.shape

(3, 3)

In [32]:
arr3.shape

(2, 2, 3)

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr[1,0]

np.int64(4)

In [5]:
arr[:,0]

array([1, 4])

In [6]:
arr[:,1]

array([2, 5])

In [7]:
arr[:,2]

array([3, 6])

In [10]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [11]:
arr[0][2]

np.int64(3)

In [13]:
arr2[0][2]
arr2[2][2]

np.int64(9)

In [15]:
print(arr2[:,1])
print(arr2[:,2])
print(arr2[:,0])

[2 5 8]
[3 6 9]
[1 4 7]


In [16]:
print(arr2[::,1:2])

[[2]
 [5]
 [8]]


In [18]:
arr[2::,]

array([], shape=(0, 3), dtype=int64)