# Reshaping

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])

In [3]:
my_arr = arr.reshape(3,2)
my_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
my_arr = arr.reshape(2,3)
my_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
# flatten and ravel are used to when u want to convert the multidimensinal array
# in single dim
# .ravel() -> it return a view
# .flatten() -> it return a copy

In [8]:
print(arr.flatten())

[1 2 3 4 5 6]


In [5]:
arr = np.array([[1,2,3],[4,5,6]])

In [9]:
print(arr.ravel())

[1 2 3 4 5 6]
